- README.md
> Ajout d'un sous-article

- README.md
Hi, this pull request is conflicting with the current state of the file. let's see, how to overcome this.
> just trying to create a conflict.

- README.md
La constitution ayant été écrite au cours du XVIIIième siècle, certaines anomalies persistait.
-  La persistance de la notion d'être suprême
- Le fait que seules les hommes soient des citoyens
- La non possibilité de la rétroactivité d'une loi malgré le précédent des crimes contre l'humanité
> Modifications à apporter sur la constitution

- README.md
les escargots terrestres demandent à être *distingués* des autres mollusques
> Ajouts de droits pour les escargots

- README.md
not overly creative, but this time not from 'master' but directly from 'changements'.
> most boring contribution possible

- README.md
Un pied ne peut avoir de pied.
Un pied dans un pied, ça serait un genre de "piedception" ?
> Correction anatomique

- README.md
Modification d'Article 1er et Article 5
Art 1er : Supression de la notion de distinction sociale. 
Art. 5 :  Rajout d'un cas de figure où la loi n'est pas parachévée.
> resolution des conflilts dans le pull request #21

- README.md
Ajout de l'article 19 qui me semble absolument capital.
> Ajout article 19 + corrections mineures

- README.md
Tout d'abord rendons à César ce qui appartient à César. Nous, peuple de cette formation, devons avoir le crédit pour ce magnifique texte.
Ensuite, les escargots, c'est plus mignon avec un dessin.
> Pour un peu de cohérence

- README.md
Article indispensable pour se prémunir de toute démocratie
> Ajout Article zéro

- README.md
> Quelques suggestions d'ajout

- README.md
Ajout de nouveaux droits pour les citoyens.
> Art 3.1 Référundum d'initiative populaire

- README.md
Le nombre 13 porte malheur.
Interdiction d'avoir un quelconque article 13.
> Evitons tout malheur

- README.md
> nouvel article

- README.md
> Lapalissade

- README.md
> Ajout d'un pied de page rebelle

- README.md
une nouvelle loi pour les insectes?
> Changements

- README.md
> Respect de l'animal

- README.md
ajout de référence à la Constitution en début de texte
> référence à la Constitution

- README.md
Une nouvelle langue pour la france
> Nouvelle langue officielle

- README.md
histoire de tester ce pull request
> Ajout d'un pied de biche rebelle

- README.md
> Il faut universaliser

- README.md
je propose l'ajout de la déclaration du bébé en 2023
> Modif ajout bebe
